# Generated by Django 4.2.9 on 2024-02-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('rainfall', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField()),
                ('humidity', models.FloatField()),
                ('solar_radiation', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.FloatField()),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
